/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface ExecuteHandler {
    }
    interface FlagHandler {
    }
    interface TraceSelector {
    }
    interface UnTraceManager {
        "appToken": string;
        "gdbVersion": string;
        "host": string;
        "inAssets": any;
        "inTC": any;
        "isBasic": boolean;
        "name": string;
        "runIsoTraceTwice": boolean;
        "showTerminals": boolean;
    }
}
declare global {
    interface HTMLExecuteHandlerElement extends Components.ExecuteHandler, HTMLStencilElement {
    }
    var HTMLExecuteHandlerElement: {
        prototype: HTMLExecuteHandlerElement;
        new (): HTMLExecuteHandlerElement;
    };
    interface HTMLFlagHandlerElement extends Components.FlagHandler, HTMLStencilElement {
    }
    var HTMLFlagHandlerElement: {
        prototype: HTMLFlagHandlerElement;
        new (): HTMLFlagHandlerElement;
    };
    interface HTMLTraceSelectorElement extends Components.TraceSelector, HTMLStencilElement {
    }
    var HTMLTraceSelectorElement: {
        prototype: HTMLTraceSelectorElement;
        new (): HTMLTraceSelectorElement;
    };
    interface HTMLUnTraceManagerElement extends Components.UnTraceManager, HTMLStencilElement {
    }
    var HTMLUnTraceManagerElement: {
        prototype: HTMLUnTraceManagerElement;
        new (): HTMLUnTraceManagerElement;
    };
    interface HTMLElementTagNameMap {
        "execute-handler": HTMLExecuteHandlerElement;
        "flag-handler": HTMLFlagHandlerElement;
        "trace-selector": HTMLTraceSelectorElement;
        "un-trace-manager": HTMLUnTraceManagerElement;
    }
}
declare namespace LocalJSX {
    interface ExecuteHandler {
    }
    interface FlagHandler {
    }
    interface TraceSelector {
    }
    interface UnTraceManager {
        "appToken"?: string;
        "gdbVersion"?: string;
        "host"?: string;
        "inAssets"?: any;
        "inTC"?: any;
        "isBasic"?: boolean;
        "name"?: string;
        "onEmitDrawComplete"?: (event: CustomEvent<any>) => void;
        "onEmitFlagChange"?: (event: CustomEvent<any>) => void;
        "onEmitQueryTrace"?: (event: CustomEvent<any>) => void;
        "onEmitSelectedTrace"?: (event: CustomEvent<any>) => void;
        "onEmitTraceResults"?: (event: CustomEvent<any>) => void;
        "runIsoTraceTwice"?: boolean;
        "showTerminals"?: boolean;
    }
    interface IntrinsicElements {
        "execute-handler": ExecuteHandler;
        "flag-handler": FlagHandler;
        "trace-selector": TraceSelector;
        "un-trace-manager": UnTraceManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "execute-handler": LocalJSX.ExecuteHandler & JSXBase.HTMLAttributes<HTMLExecuteHandlerElement>;
            "flag-handler": LocalJSX.FlagHandler & JSXBase.HTMLAttributes<HTMLFlagHandlerElement>;
            "trace-selector": LocalJSX.TraceSelector & JSXBase.HTMLAttributes<HTMLTraceSelectorElement>;
            "un-trace-manager": LocalJSX.UnTraceManager & JSXBase.HTMLAttributes<HTMLUnTraceManagerElement>;
        }
    }
}
